- name: Include vars
  include_vars: vars_ssh_relate.yaml

- name: "Centos7 关闭selinux"
  selinux: state=disabled

- name: "Centos7 关闭firewalld"
  service: name=firewalld state=stopped enabled=no

- name: "Centos7 Configure sudoers file for user user"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ ssh_user }}'
    line: '{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'

- name: "Centos7 修改sshd配置文件"
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      UseDNS no
  register: sshd_config_update

- name: "Centos7 重启sshd服务"
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd
  when:
    - sshd_config_update.changed

- name: Set vm.swappiness to 0 using sysctl
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    sysctl_set: yes
    reload: yes

- name: Ensure vm.swappiness is set in sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^vm.swappiness[[:space:]]?='
    line: 'vm.swappiness = 0'

- name: "Centos7 Check if lock file exists for yum clean metadata"
  stat:
    path: /var/cache/yum/.yum-clean-metadata-lock
  register: yum_clean_metadata_lock_file_stat

- name: "Centos7 清理缓存"
  command: yum clean metadata
  args:
    warn: no
  when: not yum_clean_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_clean_metadata_lock_file_stat.stat.mtime | int > 3600)

- name: "Centos7 Create lock file for yum clean metadata"
  file:
    path: /var/cache/yum/.yum-clean-metadata-lock
    state: touch
  when: not yum_clean_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_clean_metadata_lock_file_stat.stat.mtime | int > 3600)

- name: "Centos7 屏蔽默认源 使用新的源安装包"
  yum:
    name: yum-utils
    disablerepo: "base,extras,updates"

- name: "Centos7 Check if lock file exists for 禁用老的base extras updates源"
  stat:
    path: /var/cache/yum/.yum-disable-metadata-lock
  register: yum_disable_metadata_lock_file_stat

- name: "Centos7 禁用老的base extras updates源"
  command: yum-config-manager --disable base extras updates
  when: not yum_disable_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_disable_metadata_lock_file_stat.stat.mtime | int > 3600)

- name: "Centos7 Create lock file for 禁用老的base extras updates源"
  file:
    path: /var/cache/yum/.yum-disable-metadata-lock
    state: touch
  when: not yum_disable_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_disable_metadata_lock_file_stat.stat.mtime | int > 3600)

- name: "Centos7 Check if lock file exists for check-internet"
  stat:
    path: /var/cache/yum/.yum-check-internet-metadata-lock
  register: yum_check_internet_metadata_lock_file_stat

- name: "Check if internet is available"
  command: ping -c 1 8.8.8.8
  register: internet_access
  ignore_errors: true
  when: not yum_check_internet_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_check_internet_metadata_lock_file_stat.stat.mtime | int > 3600)

- set_fact:
    is_internet_available: "{{ internet_access.rc == 0 }}"
  when: internet_access is defined and 'rc' in internet_access

- name: "Centos7 Load outernet repo vars"
  include_vars:
    file: vars_repo_out.yaml
  when: is_internet_available is defined and is_internet_available

- name: "Centos7 Load internal repo vars"
  include_vars:
    file: vars_repo_in.yaml
  when: is_internet_available is defined and not is_internet_available

- name: "Centos7 创建并更新新的repo文件"
  template:
    src: "/root/scripts/ansible_yaml/baseepel_all.j2"
    dest: "/etc/yum.repos.d/baseepel.repo"
    owner: root
    group: root
    mode: '0644'
  when: is_internet_available is defined

- name: "Centos7 Create lock file for check-internet"
  file:
    path: /var/cache/yum/.yum-check-internet-metadata-lock
    state: touch
  when: is_internet_available is defined

- block:
    - name: "Set up cron job for time synchronization for internet hosts"
      cron:
        name: "Sync time every hour"
        minute: "0"
        hour: "*"
        user: root
        job: "/usr/sbin/ntpdate stdtime.gov.hk > /dev/null 2>&1"
  when: is_internet_available is defined and is_internet_available

- block:
    - name: "Delete server lines in ntp.conf"
      lineinfile:
        dest: /etc/ntp.conf
        regex: '^server [0-4].centos.pool.ntp.org iburst'
        state: absent
        backup: yes
        backrefs: yes

    - name: "Add internal ntp servers"
      blockinfile:
        path: /etc/ntp.conf
        block: |
          server {{ ntp_server_1 }} iburst
          server {{ ntp_server_2 }} iburst
        register: ntp_config_update

    - name: "Restart ntpd service"
      systemd:
        state: restarted
        daemon_reload: yes
        name: ntpd
        enabled: yes
      when:
        - ntp_config_update.changed
  when: is_internet_available is defined and not is_internet_available

- name: "Centos7 Check if lock file exists for yum makecache metadata"
  stat:
    path: /var/cache/yum/.yum-makecache-metadata-lock
  register: yum_makecache_metadata_lock_file_stat

- name: "Centos7 刷新源"
  command: yum makecache
  args:
    warn: no
  when: not yum_makecache_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_makecache_metadata_lock_file_stat.stat.mtime | int > 3600)

- name: "Centos7 Create lock file for yum makecache metadata"
  file:
    path: /var/cache/yum/.yum-makecache-metadata-lock
    state: touch
  when: not yum_makecache_metadata_lock_file_stat.stat.exists or (ansible_date_time.epoch | int - yum_makecache_metadata_lock_file_stat.stat.mtime | int > 3600)

- name: "Centos7 Install base software"
  yum:
    name:
      - iftop
      - zip
      - python2-pip
      - lrzsz
      - wget
      - gcc
      - gcc-c++
      - autoconf
      - automake
      - make
      - iotop
      - atop
      - vim
      - net-tools
      - samba
      - samba-client
      - ntp
      - ntpdate
      - nfs-utils
      - python3
      - python3-pip
      - tuned
    state: present

- name: Get current tuned profile
  shell: "tuned-adm active | awk -F': ' '{print $2}'"
  register: current_tuned_profile
  changed_when: False

- name: Activate network-throughput profile
  command: tuned-adm profile network-latency
  when: current_tuned_profile.stdout != "network-latency"

- name: Check if network configuration has been applied
  stat:
    path: /var/lib/network_config_applied
  register: network_config_applied

- name: Gather networking facts
  setup:
    gather_subset: network
  when: not network_config_applied.stat.exists

- name: Reset connection
  meta: reset_connection
  when: not network_config_applied.stat.exists

- name: Configure static IP
  template:
    src: /root/scripts/ansible_yaml/ifcfg-template.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
  when: not network_config_applied.stat.exists

- name: Restart network
  command: systemctl restart network
  when: not network_config_applied.stat.exists

- name: Create a flag file after network configuration
  file:
    path: /var/lib/network_config_applied
    state: touch
  when: not network_config_applied.stat.exists

- name: Check if lock file exists
  stat:
    path: /var/lib/reboot.lock
  register: lock_file_stat

- name: Create lock file
  file:
    path: /var/lib/reboot.lock
    state: touch
  when:
    - not lock_file_stat.stat.exists
    - (ansible_facts['uptime_seconds'] | int) <= 86400

- name: Restart machine if CentOS7 and no lock file exists and uptime < 1 day
  command: /sbin/reboot
  async: 0
  poll: 0
  failed_when: false
  ignore_errors: true
  ignore_unreachable: true
  when:
    - not lock_file_stat.stat.exists
    - (ansible_facts['uptime_seconds'] | int) <= 86400