---
# tasks file for send_to_mail

- name: Include secret vars
  include_vars:
    file: vars/mail_var.yaml
    name: secrets

- name: Check if file_to_send exists
  stat:
    path: "{{ item }}"
  register: result
  delegate_to: localhost
  loop: "{{ file_to_send_list }}"

- name: Fail if file_to_send does not exist
  fail:
    msg: "File {{ item.item }} does not exist!"
  when: item.stat.exists == False
  loop: "{{ result.results }}"

- name: Execute mail sending script locally
  local_action:
    module: shell
    args:
      cmd: "python3 {{ secrets.scripts_dir }}/AutoDeploy360/based_on_role_yaml/send_to_mail/files/mailsend.py {{ secrets.mail_host }} {{ secrets.from_address }} '{{ secrets.to_addresses | join(',') }}' '\"{{ mail_subject }}\"' {{ item }}"
  loop: "{{ file_to_send_list }}"
