---
# tasks file for reboot_for_centos7
- name: "Centos7 Include vars"
  include_vars: ../vars/system_info_centos7_var.yaml

- name: "Centos7 Check if lock file exists"
  stat:
    path: /var/lib/reboot.lock
  register: lock_file_stat

- name: "Centos7 Create lock file"
  file:
    path: /var/lib/reboot.lock
    state: touch
  when:
    - not lock_file_stat.stat.exists
    - (ansible_facts['uptime_seconds'] | int) <= lock_file_timeout

- name: "Centos7 Restart machine if CentOS7 and no lock file exists and uptime < 1 day"
  command: /sbin/reboot
  async: 0
  poll: 0
  failed_when: false
  ignore_errors: true
  ignore_unreachable: true
  when:
    - not lock_file_stat.stat.exists
    - (ansible_facts['uptime_seconds'] | int) <= lock_file_timeout
