---
# tasks file for install_samba_for_ubuntu20
- name: Include vars
  include_vars: ../vars/samba_var_ubuntu20.yaml

- name: Install base package
  apt:
    name:
      - smbclient
      - samba

- name: Backup smb.conf file
  command: cp /etc/samba/smb.conf /etc/samba/smb.conf.bak
  args:
    creates: /etc/samba/smb.conf.bak
  register: backup_result

- name: Check if smb.conf file needs to be cleared
  stat:
    path: /etc/samba/smb.conf
  register: smb_conf_stat

- name: Clear smb.conf file if not empty
  copy:
    content: ""
    dest: /etc/samba/smb.conf
  when: backup_result.changed and smb_conf_stat.stat.size > 0
  register: clear_smb_conf
  changed_when: clear_smb_conf.changed

- name: smb.conf file already clear
  debug:
    msg: "smb.conf file is already clear"
  when: not backup_result.changed or (backup_result.changed and smb_conf_stat.stat.size == 0)
  changed_when: false

- name: Check if samba user admin exists
  command: smbpasswd -e "{{ ssh_user }}"
  register: samba_user_check
  changed_when: false
  failed_when: samba_user_check.rc != 0 and samba_user_check.rc != 1

- name: Create samba user admin if not exists
  block:
    - name: Create samba user
      shell: "echo -e '{{ samba_user_password }}' | smbpasswd -a '{{ ssh_user }}' -s"
      args:
        executable: /bin/bash
      register: create_samba_user
      changed_when: create_samba_user.rc == 0
  when: samba_user_check.rc != 0

- name: Samba user admin already exists
  debug:
    msg: 'Samba user "{{ ssh_user }}" already exists'
  when: samba_user_check.rc == 0
  changed_when: false

- name: Write samba config to smb.conf file
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [global]
      workgroup = SAMBA
      security = user
      passdb backend = tdbsam
      printing = cups
      printcap name = cups
      load printers = yes
      cups options = raw

      [admin_home]
      valid users = {{ ssh_user }}
      path = /data
      read only = no
      browseable = yes
      guest ok = no
      
      #cli test demo 
      #smbclient //localhost/admin_home -U username
  register: samba_config_update

- name: Create directory and set permissions
  file:
    path: /data
    state: directory
    mode: '0755'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

- name: Restart samba
  systemd:
    name: smbd
    state: restarted
  when:
    - samba_config_update.changed

- name: Test samba connection
  shell: 'echo "{{ pass }}" | smbclient //localhost/{{ samba_share_name }} -U "{{ ssh_user }}" -c "mkdir testdir; put /etc/hosts testfile; get testfile; rm testfile; rmdir testdir"'
  register: samba_test_result
  changed_when: false

- name: Show samba test result
  debug:
    var: samba_test_result.stdout_lines

- name: Assert samba test success
  assert:
    that: samba_test_result.rc == 0
    fail_msg: "Samba test failed with message: {{ samba_test_result.stderr }}"

- name: Ensure smbclient is installed
  apt:
    name: smbclient
    state: present
