- hosts: ubuntu_servers
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: system_info
          when: "'system_info' in roles"

        - include_role:
            name: install_samba_for_ubuntu20
          when: "'install_samba_for_ubuntu20' in roles"

        - include_role:
            name: reboot_for_ubuntu20
          when: "'reboot_for_ubuntu20' in roles"
      when: groups['ubuntu_servers'] | length > 0

- hosts: centos_servers
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: system_info
          when: "'system_info' in roles"

        - include_role:
            name: install_samba_for_centos7
          when: "'install_samba_for_centos7' in roles"

        - include_role:
            name: reboot_for_centos7
          when: "'reboot_for_centos7' in roles"
      when: groups['centos_servers'] | length > 0
