- hosts: ubuntu_servers
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: system_info
          when: "'system_info' in roles"

        - include_role:
            name: time_clock_cron_check
          when: "'time_clock_cron_check' in roles"

        - include_role:
            name: install_nic_driver_for_ubuntu20_nuc
          when: "'install_nic_driver_for_ubuntu20_nuc' in roles"

        - include_role:
            name: install_samba_for_ubuntu20
          when: "'install_samba_for_ubuntu20' in roles"

        - include_role:
            name: install_pkg_for_ubuntu20
          when: "'install_pkg_for_ubuntu20' in roles"

        - include_role:
            name: set_nic_parameters_for_all
          when: "'set_nic_parameters_for_all' in roles"

        - include_role:
            name: reboot_for_ubuntu20
          when: "'reboot_for_ubuntu20' in roles"
      when: groups['ubuntu_servers'] | length > 0

- hosts: centos_servers
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: system_info
          when: "'system_info' in roles"

        - include_role:
            name: time_clock_cron_check
          when: "'time_clock_cron_check' in roles"

        - include_role:
            name: install_samba_for_centos7
          when: "'install_samba_for_centos7' in roles"

        - include_role:
            name: set_nic_parameters_for_all
          when: "'set_nic_parameters_for_all' in roles"

        - include_role:
            name: reboot_for_centos7
          when: "'reboot_for_centos7' in roles"
      when: groups['centos_servers'] | length > 0

- hosts: all_all
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: sshpass_ssh_conn
          when: "'sshpass_ssh_conn' in roles"

        - include_role:
            name: time_clock_cron_check
          when: "'time_clock_cron_check' in roles"

- hosts: localhost
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: send_to_mail
          when: "'send_to_mail' in roles"

- hosts: ip_proxy
  gather_facts: yes
  tasks:
    - block:
        - include_role:
            name: ip_all_collection
          when: "'ip_all_collection' in roles"
